images:
  etcd: gcr.io/google_containers/etcd-amd64:2.2.5
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port: 2379
  host: etcd

resources:
  etcd:
# No HA support, don't change this.
    replicas: 1
