# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3

resources:
  enabled: false
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled
  
upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3
auth:
  default_user: openstack
  default_pass: password
  admin_user: rabbitmq
  admin_pass: password

network:
  port:
    public: '5672'
    management: '15672'

images:
  rabbitmq: "registry.mcp.fuel-infra.org/mcp/rabbitmq:ocata-unstable"
  dep_check: "quay.io/stackanetes/kubernetes-entrypoint:v0.1.1"
  pull_policy: "IfNotPresent"

enabled_plugins:
  - autocluster

erlang_cookie: openstack-cookie

endpoints:
  etcd:
    hosts:
      default: etcd
    port: 2379

autocluster:
  log_level: info
  delay: 15

probes_delay: 180
probes_timeout: 10

dependencies:
  service:
  - etcd
