apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-etc
  labels:
    system: openstack
    type: configuration
    component: messaging
data:
  enabled_plugins: |
{{ tuple "etc/_enabled_plugins.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  erlang.cookie: |
{{ tuple "etc/_erlang.cookie.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  rabbitmq-env.conf: |
{{ tuple "etc/_rabbitmq-env.conf.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  rabbitmq.config: |
{{ tuple "etc/_rabbitmq.config.tpl" . | include  "helm-toolkit.template" | indent 4 }}

