apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-bin
  labels:
    system: openstack
    type: configuration
    component: messaging
data:
  rabbitmq-liveness.sh: |
{{ tuple "bin/_rabbitmq-liveness.sh.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  rabbitmq-readiness.sh: |
{{ tuple "bin/_rabbitmq-readiness.sh.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  rabbitmq-check-helpers.sh: |
{{ tuple "bin/_rabbitmq-check-helpers.sh.tpl" . | include  "helm-toolkit.template" | indent 4 }}
  start.sh: |
{{ tuple "bin/_rabbitmq-start.sh.tpl" . | include  "helm-toolkit.template" | indent 4 }}
